### ISSUE TITLE
Python3.12 escape sequence syntax error

### ISSUE THREAD

**Issue by gunnardag** [thrkll/ruv-dl#11]
After python3.6 escape sequences in string literals were deprecated.
After python3.12 escape sequences in string literals started throwing syntax errors.
To fix it, the string literal needs to be a raw string literal instead.

So in **ruv-dl/ruv-dl/ruv-dl.py** line 89 would need the following fix:

for this line
`title = re.sub('[^\w_.)( -]', '', title)`

add **r** in front of the string like this
`title = re.sub(r'[^\w_.)( -]', '', title)`

**Comment by thrkll** [comment]
Brilliant. Thanks for noticing and opening the issue @gunnardag.
