### ISSUE TITLE
Some links from today does not work.

### ISSUE THREAD

**Issue by starinspace** [thrkll/ruv-dl#2]
New error from links on new episodes for [example](https://www.ruv.is/sjonvarp/spila/sigildar-teiknimyndir/28386): does not work. Seems like they changed the links again.

Traceback (most recent call last):
  File "ruv-dl.py", line 108, in <module>
    main()
  File "ruv-dl.py", line 8, in main
    link()
  File "ruv-dl.py", line 20, in link
    api()
  File "ruv-dl.py", line 31, in api
    name()
  File "ruv-dl.py", line 34, in name
    multiple_episodes = api.data['multiple_episodes']
KeyError: 'multiple_episodes'

**Comment by thrkll** [comment]
This has been fixed in the latest update. 

On the other hand it seems like RUV still uses the old format for radio content. Those links will therefore throw a similar error until I fix it.

**Comment by thrkll** [comment]
All links should work now.
