### ISSUE TITLE
Only downloads a short mp3 instead of full clip and does not find subtitles.

### ISSUE THREAD

**Issue by starinspace** [thrkll/ruv-dl#3]
I only get a small *.mp3-file and there is no way to download subtitles:

https://www.ruv.is/utvarp/spila/taka-tvo/85677/ph2hej

Also is there a way to request to only download subtitles without the video as well and subtitles like english and icelandic when both is avalible?

**Comment by thrkll** [comment]
There are issues with downloading radio content with ruv-dl at the moment.
 
Ruv-dl had been completely rewritten and will be published soon. Currently there is no option to download subtitles only, but this will be possible in the next version. 

For the time being, as that link leads to a video file try entering 
https://www.ruv.is/sjonvarp/spila/taka-tvo/85677/ph2hej
and download the subtitles along with the mp4 file.

**Comment by thrkll** [comment]
Resolved with version 2.0.0.
